# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 359a767e20e8fee8de9e5ad3a1072f4b28772655a619de91022e50086e00766070dd5b98e6803cbc8d8e313c042d5a8b33fc5aab4b3e5d4107b92cceeac71dd1

test:
  secret_key_base: 5881833f80fbb960f12a3270ebada16667d184e0f44df967d107318445d0615b5eeeada5183794010529bffc561d34a919913a0a10ef05045e6f05aeed767b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
